### ISSUE TITLE
set access-control-allow-origin: * header

### ISSUE THREAD

**Issue by noerw** [sensebox/sensebox-sketches#15]
With the current implementation of the upcoming [Blockly / OTA programming mobile app](https://github.com/AppDevelopmentAtsenseBox/openSenseApp), access from web-browsers running on the phone's `localhost` domain is required.

If the current access restriction is implemented to minimize load, alternative methods such as a rate-limiter come to mind.

**Comment by mpfeil** [comment]
Let´s set it to `*` and see how the load will behave.
